name: GLuaTest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      gamemode: extremefootballthrowdown
      # If any Workshop addons are required for the test environment, add them here:
      # requirementModules: |
      #   - workshopId: 1234567
